MODULES_DIR = 'modules'

MOD_CONFIG_ROUTES_MOD_KEY = 'routes_mod'
MOD_CONFIG_ROUTES_MOD_DEFAULT = 'routes'

MOD_CONFIG_MOD_VAR_KEY = 'module_var'
MOD_CONFIG_MOD_VAR_DEFAULT = 'module'

MOD_CONFIG_URL_PREFIX_KEY = 'url_prefix'

MOD_CONFIG_MOD_NAME_KEY = 'module_name'